---
plex_port: 32400
plex_dlna_port: 1900
plex_bonjour_port: 5353
plex_roku_port: 8324
plex_gdm_port1: 32410
plex_gdm_port2: 32412
plex_gdm_port3: 32413
plex_gdm_port4: 32414
plex_dlna_server_port: 32469
plex_folder: /etc/plex
plex_tv_folder: /storage/tv
plex_movies_folder: /storage/movies
plex_music_folder: /storage/music
plex_tz: "America/Los_Angeles"
plex_dvb_devices: false
plex_dri_devices: false
plex_claim: ""
plex_memory: "1g"
plex_memory_swap: "1g"
