---
dependencies:
  - role: media_user
galaxy_info:
  author: Jason Ernst
  role_name: media_storage
  description: Creates shared media storage directories for all media server components
  company: ""
  license: GPLv3
  min_ansible_version: "2.4"
  platforms:
    - name: Ubuntu
      versions:
        - bionic # 18.04 LTS
        - focal # 20.04 LTS
        - jammy # 22.04 LTS
        - noble # 24.04 LTS
  galaxy_tags:
    - media
    - storage
    - directories
