---
# Docker installation control
lidarr_install_docker: false

# Lidarr configuration
lidarr_folder: /etc/lidarr
lidarr_music_folder: /storage/music
lidarr_transmission_downloads_folder: /storage/downloads
lidarr_sabnzbd_downloads_folder: /storage/downloads
lidarr_port: 8686
lidarr_tz: "America/Los_Angeles"
lidarr_memory: "1g"
lidarr_memory_swap: "1g"
