---
# Docker installation control
lidarr_install_docker: false

# Lidarr configuration
lidarr_plugins: false
lidarr_folder: /etc/lidarr
lidarr_music_folder: "{{ media_storage_base_path }}/music"
lidarr_transmission_downloads_folder: "{{ media_storage_base_path }}/downloads"
lidarr_sabnzbd_downloads_folder: "{{ media_storage_base_path }}/downloads"
lidarr_port: 8686
lidarr_tz: "America/Los_Angeles"
lidarr_memory: "1g"
lidarr_memory_swap: "1g"
