---
transmission_port: 9091
transmission_peer_port: 51413
transmission_folder: /etc/transmission
transmission_downloads_folder: /storage/downloads
transmission_pid: "1000"
transmission_gid: "1000"
transmission_tz: "America/Los_Angeles"
transmission_env_file: "{{ transmission_folder }}/.env"
transmission_memory: "1g"
transmission_memory_swap: "1g"

# Docker network (use custom network for container name resolution)
transmission_networks: []
