---
# Docker installation control
radarr_install_docker: false

# Radarr configuration
radarr_folder: /etc/radarr
radarr_movies_folder: /storage/movies
radarr_transmission_downloads_folder: /storage/downloads
radarr_sabnzbd_downloads_folder: /storage/downloads
radarr_port: 7878
radarr_tz: "America/Los_Angeles"
radarr_memory: "1g"
radarr_memory_swap: "1g"
