---
dependencies:
  - role: media_storage
galaxy_info:
  author: Jason Ernst
  role_name: slskd
  description: Installs and configures the slskd (Soulseek) container
  company: ""
  license: GPLv3
  min_ansible_version: "2.4"
  platforms:
    - name: Ubuntu
      versions:
        - bionic # 18.04 LTS
        - focal # 20.04 LTS
        - jammy # 22.04 LTS
        - noble # 24.04 LTS
  galaxy_tags:
    - docker
    - slskd
    - soulseek
    - music
    - p2p
